CREATE DATABASE ChamaJussaBD;
GO
USE ChamaJussaBD;
GO

CREATE TABLE Usuario(
	IdUsuario VARCHAR(40) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) UNIQUE NOT NULL,
	Senha VARCHAR(60) NOT NULL,
	FotoPerfil VARCHAR(100)
);
GO

CREATE TABLE OrdemServico(
	IdOS VARCHAR(40) PRIMARY KEY,
	NumeroOS VARCHAR(20) UNIQUE NOT NULL,
	TituloProblema VARCHAR(200) NOT NULL,
	MaquinaEquipamento VARCHAR(150) NOT NULL,
	LocalSetor VARCHAR(150) NOT NULL,
	DescricaoProblema VARCHAR(MAX) NOT NULL,
	FotoProblema VARCHAR(100),
	Status VARCHAR(20) NOT NULL,
	IdUsuario VARCHAR(40) FOREIGN KEY REFERENCES Usuario(IdUsuario)
);
GO

CREATE TABLE Notificacao(
	IdNotificacao VARCHAR(40) PRIMARY KEY,
	Titulo VARCHAR(150) NOT NULL,
	Mensagem VARCHAR(300) NOT NULL,
	Lida BIT NOT NULL,
	IdUsuario VARCHAR(40) FOREIGN KEY REFERENCES Usuario(IdUsuario),
	IdOS VARCHAR(40) FOREIGN KEY REFERENCES OrdemServico(IdOS)
);
GO